# Generated by Django 5.0.7 on 2024-07-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='dummy', max_length=255),
            preserve_default=False,
        ),
    ]
